[project]
name = "advent-of-code-2024"
version = "0.1.0"
description = "Solutions for Advent of Code 2024."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.5",
    "numpy>=2.3.1",
    "tqdm>=4.67.1",
]
